# -*- coding: utf-8 -*-
"""Flood_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_Y4OI7ok7NV-ESx5APslEWKTbhu15s7
"""

import pandas as pd

# Load datasets
events = pd.read_csv("floodevents_indofloods.csv")
rain = pd.read_csv("precipitation_variables_indofloods.csv")
metadata = pd.read_csv("metadata_indofloods.csv")
catchment = pd.read_csv("catchment_characteristics_indofloods.csv")

# Merge events + precipitation (1:1 on EventID)
df = events.merge(rain, on="EventID")

df.head()

df.to_csv("Events_ID.csv", index=False)

import pandas as pd

events = pd.read_csv("floodevents_indofloods.csv")
rain = pd.read_csv("precipitation_variables_indofloods.csv")
metadata = pd.read_csv("metadata_indofloods.csv")
catchment = pd.read_csv("catchment_characteristics_indofloods.csv")

df = events.merge(rain, on="EventID")

print("After events+rain:", df.shape)

df["EventID"] = df["EventID"].astype(str).str.strip()
df["GaugeID"] = df["EventID"].str.rsplit("-", n=1).str[0]

df = df.merge(metadata, on="GaugeID", how="left")

print("After metadata merge:", df.shape)
print("Missing metadata:", df["Station"].isna().sum())

df = df.merge(catchment, on="GaugeID", how="left")

print("After catchment merge:", df.shape)
print("Missing catchment:", df["Drainage Area"].isna().sum())

print(df["Flood Type"].unique())

print(df.isna().sum().sum())

important_columns = [
    # Rainfall
    "T1d","T2d","T3d","T4d","T5d","T6d","T7d","T8d","T9d","T10d",

    # Flood info
    "Flood Type",

    # Catchment physical features
    "Drainage Area",
    "Catchment Relief",
    "Drainage Density",
    "Ruggedness Number",

    # Metadata
    "Latitude",
    "Longitude"
]

df = df[important_columns]

df["Flood Type"] = df["Flood Type"].str.strip()
df["Flood_Label"] = df["Flood Type"].map({
    "Flood": 0,
    "Severe Flood": 1
})

print(df.isna().sum())

print(df.shape)
print(df["Flood_Label"].value_counts())

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from xgboost import XGBClassifier

X = df.drop(["Flood Type", "Flood_Label"], axis=1)
y = df["Flood_Label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt

plt.bar(X.columns, model.feature_importances_)
plt.xticks(rotation=90)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from xgboost import XGBClassifier

# ---------------------------
# Prepare Data
# ---------------------------

X = df.drop(["Flood Type", "Flood_Label"], axis=1)
y = df["Flood_Label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ---------------------------
# Handle Class Imbalance
# ---------------------------

scale_pos_weight = len(y_train[y_train == 0]) / len(y_train[y_train == 1])

# ---------------------------
# Improved Model
# ---------------------------

model = XGBClassifier(
    n_estimators=400,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric="logloss"
)

model.fit(X_train, y_train)

# ---------------------------
# Threshold Adjustment
# ---------------------------

y_prob = model.predict_proba(X_test)[:, 1]

# Lower threshold to increase severe recall
threshold = 0.40
y_pred = (y_prob > threshold).astype(int)

# ---------------------------
# Evaluation
# ---------------------------

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# ---------------------------
# Feature Importance Plot
# ---------------------------

plt.figure(figsize=(10,6))
plt.bar(X.columns, model.feature_importances_)
plt.xticks(rotation=90)
plt.title("Feature Importance")
plt.tight_layout()
plt.show()

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# ---------------------------
# Preview Dataset
# ---------------------------

print("Shape of dataset:", df.shape)
print("\nColumns:")
print(df.columns)

print("\nFirst 5 rows:")
print(df.head())

print("\nClass distribution:")
print(df["Flood_Label"].value_counts())

# ---------------------------
# Save to CSV
# ---------------------------

output_filename = "final_merged_flood_severity_dataset.csv"

df.to_csv(output_filename, index=False)

print(f"\nDataset successfully saved as '{output_filename}'")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from xgboost import XGBClassifier

# ---------------------------------------
# Separate Classes
# ---------------------------------------

df_flood = df[df["Flood_Label"] == 0]
df_severe = df[df["Flood_Label"] == 1]

# Shuffle both classes
df_flood = shuffle(df_flood, random_state=42)
df_severe = shuffle(df_severe, random_state=42)

# ---------------------------------------
# Create Balanced Test Set (326 each)
# ---------------------------------------

test_flood = df_flood.iloc[:326]
test_severe = df_severe.iloc[:326]

df_test = pd.concat([test_flood, test_severe])
df_test = shuffle(df_test, random_state=42)

# ---------------------------------------
# Create Balanced Train Set (1629 each)
# ---------------------------------------

train_flood = df_flood.iloc[326:326+1629]
train_severe = df_severe.iloc[326:326+1629]

df_train = pd.concat([train_flood, train_severe])
df_train = shuffle(df_train, random_state=42)

print("Train distribution:")
print(df_train["Flood_Label"].value_counts())

print("\nTest distribution:")
print(df_test["Flood_Label"].value_counts())

# ---------------------------------------
# Separate Features and Labels
# ---------------------------------------

X_train = df_train.drop(["Flood Type", "Flood_Label"], axis=1)
y_train = df_train["Flood_Label"]

X_test = df_test.drop(["Flood Type", "Flood_Label"], axis=1)
y_test = df_test["Flood_Label"]

# ---------------------------------------
# Train XGBoost (No class weight needed now)
# ---------------------------------------

model = XGBClassifier(
    n_estimators=400,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

model.fit(X_train, y_train)

# ---------------------------------------
# Predict
# ---------------------------------------

y_pred = model.predict(X_test)

# ---------------------------------------
# Evaluation
# ---------------------------------------

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)

# ---------------------------------------
# Feature Importance
# ---------------------------------------

plt.figure(figsize=(10,6))
plt.bar(X_train.columns, model.feature_importances_)
plt.xticks(rotation=90)
plt.title("Feature Importance")
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from xgboost import XGBClassifier

# ======================================================
# 1️⃣ FEATURE ENGINEERING
# ======================================================

# ----- Rainfall aggregated features -----
df["Rain_3day"] = df["T3d"]
df["Rain_5day"] = df["T5d"]
df["Rain_7day"] = df["T7d"]
df["Rain_10day"] = df["T10d"]

df["Rain_1to3_ratio"] = df["T1d"] / (df["T3d"] + 1e-6)
df["Rain_growth_3to7"] = df["T7d"] - df["T3d"]

# ----- Interaction features -----
df["Rain7_Area"] = df["Rain_7day"] * df["Drainage Area"]
df["Rain7_Rugged"] = df["Rain_7day"] * df["Ruggedness Number"]
df["Rain7_Relief"] = df["Rain_7day"] * df["Catchment Relief"]

df["Log_Drainage_Area"] = np.log1p(df["Drainage Area"])

# ----- Remove raw rainfall columns -----
df = df.drop(
    ["T1d","T2d","T3d","T4d","T5d","T6d","T7d","T8d","T9d","T10d"],
    axis=1
)

print("Dataset shape after feature engineering:", df.shape)

# ======================================================
# 2️⃣ BALANCED TRAIN / TEST SPLIT
# ======================================================

df_flood = df[df["Flood_Label"] == 0]
df_severe = df[df["Flood_Label"] == 1]

df_flood = shuffle(df_flood, random_state=42)
df_severe = shuffle(df_severe, random_state=42)

# ----- Test set (326 each) -----
test_flood = df_flood.iloc[:326]
test_severe = df_severe.iloc[:326]

df_test = pd.concat([test_flood, test_severe])
df_test = shuffle(df_test, random_state=42)

# ----- Train set (remaining data) -----
train_flood = df_flood.iloc[326:]
train_severe = df_severe.iloc[326:]

df_train = pd.concat([train_flood, train_severe])
df_train = shuffle(df_train, random_state=42)

print("\nTrain distribution:")
print(df_train["Flood_Label"].value_counts())

print("\nTest distribution:")
print(df_test["Flood_Label"].value_counts())

# ======================================================
# 3️⃣ SEPARATE FEATURES & LABELS
# ======================================================

X_train = df_train.drop(["Flood Type", "Flood_Label", "Latitude", "Longitude"], axis=1)
y_train = df_train["Flood_Label"]

X_test = df_test.drop(["Flood Type", "Flood_Label", "Latitude", "Longitude"], axis=1)
y_test = df_test["Flood_Label"]

# ======================================================
# 4️⃣ MODEL TRAINING
# ======================================================

model = XGBClassifier(
    n_estimators=500,
    max_depth=3,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

model.fit(X_train, y_train)

# ======================================================
# 5️⃣ PREDICTION
# ======================================================

y_pred = model.predict(X_test)

# ======================================================
# 6️⃣ EVALUATION
# ======================================================

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)

# ======================================================
# 7️⃣ FEATURE IMPORTANCE
# ======================================================

plt.figure(figsize=(10,6))
plt.bar(X_train.columns, model.feature_importances_)
plt.xticks(rotation=90)
plt.title("Feature Importance")
plt.tight_layout()
plt.show()

!pip install lightgbm

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from lightgbm import LGBMClassifier

# --------------------------------------------
# Ensure clean copy
# --------------------------------------------
df = df.copy()

# --------------------------------------------
# Balanced Split (326 test each)
# --------------------------------------------

df_flood = df[df["Flood_Label"] == 0]
df_severe = df[df["Flood_Label"] == 1]

df_flood = shuffle(df_flood, random_state=42)
df_severe = shuffle(df_severe, random_state=42)

# Test set
test_flood = df_flood.iloc[:326]
test_severe = df_severe.iloc[:326]

df_test = pd.concat([test_flood, test_severe])
df_test = shuffle(df_test, random_state=42)

# Balanced train set
train_flood = df_flood.iloc[326:326+1303]
train_severe = df_severe.iloc[326:]

df_train = pd.concat([train_flood, train_severe])
df_train = shuffle(df_train, random_state=42)

print("Train distribution:")
print(df_train["Flood_Label"].value_counts())

print("\nTest distribution:")
print(df_test["Flood_Label"].value_counts())

# --------------------------------------------
# Separate features and labels
# --------------------------------------------

X_train = df_train.drop(["Flood Type", "Flood_Label", "Latitude", "Longitude"], axis=1)
y_train = df_train["Flood_Label"]

X_test = df_test.drop(["Flood Type", "Flood_Label", "Latitude", "Longitude"], axis=1)
y_test = df_test["Flood_Label"]

# --------------------------------------------
# LightGBM Model (Shallow Trees)
# --------------------------------------------

model = LGBMClassifier(
    n_estimators=600,
    max_depth=3,              # shallower trees
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

# --------------------------------------------
# Prediction
# --------------------------------------------

y_pred = model.predict(X_test)

# --------------------------------------------
# Evaluation
# --------------------------------------------

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)

# --------------------------------------------
# Feature Importance
# --------------------------------------------

plt.figure(figsize=(10,6))
plt.bar(X_train.columns, model.feature_importances_)
plt.xticks(rotation=90)
plt.title("LightGBM Feature Importance")
plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd

from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# -------------------------------------------------
# Prepare Features and Labels
# -------------------------------------------------

X = df.drop(["Flood Type", "Flood_Label", "Latitude", "Longitude"], axis=1)
y = df["Flood_Label"]

# -------------------------------------------------
# Stratified K-Fold Cross Validation
# -------------------------------------------------

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []

# -------------------------------------------------
# LightGBM Model (Shallow Trees)
# -------------------------------------------------

model = LGBMClassifier(
    n_estimators=700,
    max_depth=3,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

# -------------------------------------------------
# Cross-Validation Loop
# -------------------------------------------------

for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), 1):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    accuracy_scores.append(accuracy_score(y_test, y_pred))
    precision_scores.append(precision_score(y_test, y_pred))
    recall_scores.append(recall_score(y_test, y_pred))
    f1_scores.append(f1_score(y_test, y_pred))

    print(f"Fold {fold} accuracy: {accuracy_scores[-1]:.4f}")

# -------------------------------------------------
# Final Results
# -------------------------------------------------

print("\n===== CROSS-VALIDATION RESULTS =====")
print("Mean Accuracy :", np.mean(accuracy_scores))
print("Mean Precision:", np.mean(precision_scores))
print("Mean Recall   :", np.mean(recall_scores))
print("Mean F1-score :", np.mean(f1_scores))